version: '3.8'

services:
  dumper_bot:
    container_name: dumper_bot
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: dumper_cache
    restart: always
