version: '3.9'

services:
  dumper_bot:
    container_name: dumper_bot
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: dumper_cache
    restart: always
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    container_name: tourism_db
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
