"""alter fields

Revision ID: 80db083a5595
Revises: f936ca42d6f2
Create Date: 2025-05-30 11:54:39.601175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80db083a5595'
down_revision: Union[str, None] = 'f936ca42d6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('databases', 'interval',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False,
               postgresql_using='interval::integer'
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('databases', 'interval',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
